name: amap
services:
    golang:
        container_name: geo
        environment:
            - RADIUS=100 # Search radius range: 0~3000, default value: 1000. Unit: meter.
            - EXTENSIONS=base # The default value of the extensions parameter is base, which means that basic address information will be returned; when the value of the extensions parameter is all, basic address information, nearby POI content, road information, and road intersection information will be returned.
            - KEY=xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx # The user applies for a Web service API type Key on the official website of AutoNavi Map.
            - MYSQL_HOST=192.168.1.9
            - MYSQL_PORT=3306
            - OCR_HOST=192.168.1.9
            - OCR_PORT=8080
        volumes:
            - ./data:/data # coordinates.txt must inside
        image: zhangyiming748/amap:latest
    ocr:
        container_name: ocr
        ports:
            - 8080:8080
        image: otiai10/ocrserver